### ISSUE TITLE
Possible to add device with empty fields with REST API

### ISSUE THREAD

**Issue by Sviests** [gotthardp/lorawan-server#139]
Hi! I managed to add a device using the rest api without filling any fields. What I now have is a device showing without any fields and without a possibility to edit it or even delete it!

![image](https://user-images.githubusercontent.com/8798050/27694232-2ac155ca-5cf4-11e7-961e-81178f23fafe.png)

**Comment by gotthardp** [comment]
Interesting :) Could you tell me what HTTP DELETE request is sent when you try to delete that row? (You can check this in Mozilla via the Developer menu -- Network.

**Comment by Sviests** [comment]
I see what the problem is, it is trying to send a DELETE request to /devices/ with an empty DevEUI and the allowed methods for /devices are only GET, POST and OPTIONS. So the response to the DELETE request is a 405 Method Not Allowed.

**Comment by gotthardp** [comment]
Allright, you need to modify the database directly.

Connect to a running lorawan-server by `erl -sname test -remsh lorawan@localhost`, where instead of `localhost` use the short hostname of the machine hosting the server (`hostname --short`).

Then delete the entry by `mnesia:dirty_delete(devices, undefined)`, which should return `ok`.

Then close the remote shell and you're done.

**Comment by Sviests** [comment]
Ok, thanks for the instructions!

**Comment by gotthardp** [comment]
Please let me know if/how it worked.

**Comment by gotthardp** [comment]
Fixed in v0.4.6
