### ISSUE TITLE
OTAA:  same AppKey and AppEUI for all the sensors 

### ISSUE THREAD

**Issue by kazi93** [gotthardp/lorawan-server#203]
@gotthardp It is possible to add same AppKey and AppEUI for all the sensors ? Please I would like to know the pros and cons. Thank you

**Comment by gotthardp** [comment]
Hello. It can be done, but with security drawbacks. If you set the same AppKey then once an attacker obtains an AppKey of one unit (e.g. by stealing and reverse engineering it), all other units will be compromised too. If the likelihood there will be such hacker is low (e.g. because its a closed area) then you make be safe.
