### ISSUE TITLE
unknown_appid

### ISSUE THREAD

**Issue by Mels67** [gotthardp/lorawan-server#264]
I do get this red box all the time: unknown_appid
I also do not get any acknowledge back to my Lora device?
![schermafbeelding 2018-01-03 om 16 02 41](https://user-images.githubusercontent.com/35070113/34525532-92d72236-f09f-11e7-8b3d-9331754c8b35.png)

**Comment by waynestallwood-kcom** [comment]
This caught me out too and it's due to there being no associated backend for the received data.

Have you defined some sort of connector, what are you doing with the data once it hits the lorawan-server ? 

Everything needs to be in a group of the same name (if your devices are then nodes will inherit the device group when the device first joins) Then if you have set the application as (backend) then the handler and connector also need to be in the same group as the devices/nodes.

At the moment if you look in (Received Frames) you'll probably find the application field is blank for the frames from your device.

You'll only get an ack back from the gateway if the device is sending a confirmed uplink, and be careful as too many confirmed uplinks (given the frequency you are sending packets) might cause your gateway to go over the permitted radio on time duty cycle for your area.

**Comment by Mels67** [comment]
Thanks Wayne, that was the trick. I already had a mqtt connector but no handler and devices and gateway not in a group! Since I changed it, everything works fine now and MQTT server is receiving the data. thanks again!
