### ISSUE TITLE
Error on downlink

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#356]
If I send a new downlink to node via MQTT I have three messages queued

**Comment by gotthardp** [comment]
Then you hit the button 3x, or there were 2 messages aready queued. Please be specific about the issue and provide enough information for debugging.

**Comment by webfrank** [comment]
I sent only one message using MQTT but i found three messages queued

<img width="1073" alt="schermata 2018-04-03 alle 12 13 48" src="https://user-images.githubusercontent.com/4688664/38243657-83551a72-3738-11e8-82a1-d42fc849acad.png">

**Comment by gotthardp** [comment]
Could you have published 3 messages accidentally? Other people don't seem to have this problem.

**Comment by webfrank** [comment]
No, every downlink I send gets multiplied :(

**Comment by altishchenko** [comment]
Sorry to interrupt, my two cents:
How many devices do you have?
What are the topics settings on the connector?

**Comment by webfrank** [comment]
Yes, I have 3 mqtt connectors as I cannot link 3 handlers to the same connector (see previous issue)

**Comment by altishchenko** [comment]
Then, there are two screenshots. Handler and typical connector.

**Comment by webfrank** [comment]
Here are the screenshots but the problem is that I want to use the same connector for several handlers but as I cannot link multiple handlers to one connector I had to duplicate connectors. This is why I got 3 messages queued, one for every connector configured.

![schermata 2018-04-04 alle 07 54 22](https://user-images.githubusercontent.com/4688664/38290855-712912fe-37dd-11e8-8178-2d0dcb6f5d80.png)
![schermata 2018-04-04 alle 07 53 50](https://user-images.githubusercontent.com/4688664/38290858-71aa6f0c-37dd-11e8-94e4-69d42672760e.png)
![schermata 2018-04-04 alle 07 53 40](https://user-images.githubusercontent.com/4688664/38290859-71caca0e-37dd-11e8-8b01-df37cb56a887.png)
![schermata 2018-04-04 alle 07 53 24](https://user-images.githubusercontent.com/4688664/38290860-71f2e336-37dd-11e8-9565-03b8a25dea4a.png)

**Comment by gotthardp** [comment]
So you connected 3 connectors to the same handler and subscribed each of the connector to the same MQTT topic? In such case it is expected you will get 3 messages, isn't it?

**Comment by altishchenko** [comment]
@webfrank the way you configured your connector is fine, when it is single on your server. If have multiple connectors configured the same, then each of them will get a message back, the received topic filter will work correctly on each of them resulting in a correct message for the existing device, hence your multiplication. You should subscribe to 'xxx/{devaddr}/downlink' in such situation.

**Comment by webfrank** [comment]
Ok but doesn't would be better to have multiple handlers for one connector? I changed the configuration of topics prefixing with app name and now I have messages queued correctly.

**Comment by altishchenko** [comment]
No no, you got it wrong a bit. The way you configured you connector **is the way** for multiple handlers-OneConnector scenario, this is how it was visioned and implemented. You stated that you have three similar connectors - hence you have to specific on each one of them. If your issue with uplink is somewhat cured, try going back to a single connector. Don't forget to change the handlers first :)

**Comment by altishchenko** [comment]
@webfrank I didn't migrate from 0.4 in a production system yet and 0.5 is running on a test bed with a small number of devices... The behaviour you want **was the behaviour** of 0.4.13. I am not sure why Petr has changed that. I just checked with the server and I believe it is a stopping problem for my future migration too... @gotthardp Petr can you comment on that?

**Comment by gotthardp** [comment]
I'm afraid that for now a Connector can be assigned to one Application/Handler only. This was done to limit the complexity of the templated connections (one MQTT connection/subscription per device). I thought that creating one connector for each Handler is not a big issue compared to the nightmare of implementing templated connections from multiple handlers.

**Comment by altishchenko** [comment]
@gotthardp : Petr, I understand that - I scanned the new code and it is architectural = means no easy way out, but the real problem lies elsewhere. Look, I have this setup with 0.4.13+ at the moment: there is a number of servers running, there is quite a number of different types of devices with different binary data transmitted, but all of that is handled on a central broker cluster that notifies different **applications** that decide their actions next. Unfortunately, this is a mine (uranium mine for that) and a life and death situation, so quite a number of vendor-made apps are sitting on the broker and deciding if they should raise the ambulance or fire brigade and such. Having a separate connector for **each** special **type** of the device is not that handy - this is what handlers are for, running 100+ parallel similar connections from a server to the broker cluster is not a very good situation either. Esp, in the middle of Taiga... :) (The sensors/motes we are talking about are everything from fall detection to radiation meters + gps/glonass positioning, on the head hit and strength counter, etc..) Most of them are embedded into the workers helmets.

**Comment by gotthardp** [comment]
The request to have multiple handlers connected to one connector is Issue #339.
The other points were clarified, so I am closing this.
