### ISSUE TITLE
cant join after reaching a certain RSSI 

### ISSUE THREAD

**Issue by gmbankar37** [gotthardp/lorawan-server#466]
Hello , 
 During my range testing of LoRa I have found out that after reaching a certain level of RSSI it doesn't join. When my RSSI goes below -110 the node is not able to join the lorawan-server. Is there any setting which restricts this action? Thank you.

**Comment by altishchenko** [comment]
Never saw this on the server side, but saw such settings in some LoRa modems. Does the server see the join request? Or everything just goes silent?

**Comment by gotthardp** [comment]
This is quite common behavior if your device has a small antenna. LoRa can receive frames till -120 dBm, but the RF characteristics of the uplink and downlink channel may be **assymetrical**. Since the device antenna has worse characteristics, I observed that the downlink RSSI is often smaller than the uplink RSSI, so if your uplink is -110dBm your downlink can easily be -125dBm, which is bellow what the device can receive. So the server receives the uplink (because it has better antenna), but the device is not able to receive the downlink as it's bellow -120.

**Comment by gmbankar37** [comment]
No the server doesnt see the join request. The whole point is that it is
not able to join. the signal might be too weak? this doesnt seems to be the
case because I still can receive an uplink with RSSI lower than -110 given
that it was already joined.
It keeps trying to join but then I get timeout response. I am using RAK831
as gateway.

**Comment by gotthardp** [comment]
I wonder how do you know your uplink is -110 when the server cannot see the join request? I still believe its because the signal is too weak. Anyway, if the gateway is not able to receive the uplink, there is not much the server can do.

**Comment by gmbankar37** [comment]
I am using a small 868MHz 3dB gain antenna.Do have any suggestions about
antenna at both node and gateway?
